### ISSUE TITLE
Неверный расчёт итогового баланса при пополнении сберегательного счета на сумму, меньше максимального баланса

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#1]
### Описание
При пополнении баланса на сумму 3_000 неверно рассчитывается сумма итогового баланса сберегательного счета
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68
### Шаги воспроизведения

1. Создать объект add класса SavingAccount согласно требованиям документации;
2. Создать тест на объект add в классе SavingAccountTest;
3. Создать метод account для пополнения счета;
4. Присвоить значение начальному балансу  - 2_000;
5. Присвоить значение минимальному балансу - 1_000;
6. Присвоить значение максимальному балансу - 10_000;
7. Присвоить значение ставки - 5;
8. Пополнить счет на 3_000;
9. Запустить тест.

_Ожидаемый результат_: После пополнения баланса сберегательного счета на 3_000 сумма итогового баланса равна 5_000.

_Фактический результат_: После пополнения баланса сберегательного счета на 3_000 сумма итогового баланса равна 3_000.

### Тест для проверки объекта add
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/5d34b7eb-f474-42c3-851d-7bf9676dd230)

### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
## Исправлено в коммите `Fix 8`. 

[Fix #8](https://github.com/migbaranes/Team_project_JAVA/issues/8)
