### ISSUE TITLE
Неверно указан тип данных для переменных суммы баланса и ставки в классе Account 

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#10]
### Описание
В классе `Account` переменные(balance, rate) объявлены с типом int, хотя значения переменных могут быть и дробные.
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/Account.java#L3
### Шаги воспроизведения

1. Зайти в проект на GitHub по ссылке: https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/Account.java
2. Посмотреть строки #L4-5
_Ожидаемый результат_: в строках находятся переменные с типом double (double balance, double rate).
_Фактический результат_: в строках находятся переменные с типом int (int balance, int rate).
### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/681611de-9750-459f-a4ab-27d2566b1b08)
### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
## Закрыто при уточнении условий задачи!!!
