### ISSUE TITLE
Неверно указаны типы переменных сумм в классе SavingAccount

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#12]
### Описание
В классе SavingAccount переменные( minBalance, maxBalance, rate, initialBalance) объявлены с типом int, хотя значения переменных могут быть и дробные.
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22
### Шаги воспроизведения

1. Зайти в проект на GitHub по ссылке:https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22
2. Посмотреть строку#L22

_Ожидаемый результат:_ в строках находятся переменные с типом double( double minBalance, double maxBalance, double rate, double initialBalance).

_Фактический результат_: в строках находятся переменные с типом int ( int minBalance, int maxBalance, int rate, int initialBalance).
### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/2dda8fec-b13c-4467-b174-837e5bb85ba1)
### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
## Закрыто при уточнении условий задачи!!
