### ISSUE TITLE
В классе SavingAccount не хватает сеттера для минимального баланса

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#13]
### Описание
По условию проекта минимальный баланс не может быть отрицательным, для проверки этого условия необходим setter на minBalance.
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L92
### Шаги воспроизведения:
1. Открыть GitHab;
2. Пройти по ссылке на проект в класс SavingAccount: https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java
3. Проверить SavingAccount на наличие setMinBalance.
_Ожидаемый результат:_  в классе SavingAccount есть setMinBalance для реализации условия проекта(минимальный баланс не может быть отрицательным).
_Фактический результат:_ в классе SavingAccount нет setMinBalance.
### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/9b20f9a9-4464-4165-86e3-da1180a8657b)

### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
`setMinBalance` добавлен в класс `SavingAccount`!
