### ISSUE TITLE
В классе SavingAccount отсутствует сеттер на максимальный баланс

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#14]
### Описание
По условию проекта maxBalance не может быть меньше 0. Для проверки этого условия необходимо создать setter для maxBalance.
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L96
### Шаги воспроизведения

1. Открыть GitHab;
2. Пройти по ссылке на проект в класс SavingAccount: https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java
Проверить SavingAccount на наличие setMinBalance.
_Ожидаемый результат:_ в классе SavingAccount есть setMaxBalance для реализации условия проекта(минимальный баланс не может быть отрицательным).
_Фактический результат:_ в классе SavingAccount нет setMaxBalance.
### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/59539aa0-c8c7-42a2-8f26-bc25ad897ab9)
### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
`setMaxBalance` добавлен в класс `SavingAccount`.
