### ISSUE TITLE
В классе SavingAccount отсутствует исключение вида IllegalArgumentException на сравнение минимального баланса с максимальным

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#15]
### Описание
По заданию проекта, если минимальный баланс больше максимального, должно выбрасываться исключение "Минимальный баланс не может быть больше максимального, а у вас: " + minBalance +maxBalance
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L15
### Шаги воспроизведения

1. Открыть GitHab;
2. Пройти по ссылке на проект в класс SavingAccount: https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java
3. Проверить SavingAccount на наличие исключений по условию: минимальный баланс не может быть больше максимального.
_Ожидаемый результат:_ в классе SavingAccount есть throw new IllegalArgument.
_Фактический результат:_ в классе SavingAccount нет throw new IllegalArgumentException.
### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/fc37df56-4b21-45a2-869f-dc2381b1d747)
### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
`IllegalArgumentException` на сравнение минимального баланса с максимальным добавлен в класс `SavingAccount`.
