### ISSUE TITLE
В классе SavingAccount отсутствует исключение вида IllegalArgumentException на отрицательное значение начального баланса

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#16]
### Описание
По заданию проекта, если начальный баланс отрицательный, должно выбрасываться исключение "Начальный баланс не может быть отрицательный, а у вас: " + initialBalance
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L15
### Шаги воспроизведения

1. Открыть GitHab;
2. Пройти по ссылке на проект в класс SavingAccount: https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java
3. Проверить SavingAccount на наличие исключений по условию: начальный баланс не может отрицательным.
_Ожидаемый результат_: в классе SavingAccount есть throw new IllegalArgument на данное условие.
_Фактический результат_: в классе SavingAccount нет throw new IllegalArgumentException на данное условие.
### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/d7ab40e6-68e2-4b89-b935-1370891be135)
_Окружение_

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
`IllegalArgumentException` на отрицательное значение начального баланса добавлен в класс `SavingAccount`
