### ISSUE TITLE
Отсутствует исключение вида `IllegalArgumentException` в классе `CreditAccount` на отрицательное значение `creditLimit`

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/Team_project_JAVA#20]
## Описание
В соответствии с требования на класс `CreditAccount`, "@param creditLimit -неотрицательное число, максимальная сумма которую можно задолжать банку", иначе должно выкидываться исключения вида `IllegalArgumentException`.

## Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/197a73a36e0087d51295bf8ff1ee47d903a5d5c1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L17

## Шаги воспроизведения

1. Открыть GitHab;
2. Пройти по ссылке на проект в класс `CreditAccount`: https://github.com/migbaranes/Team_project_JAVA/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L17
3. Проверить CreditAccount на наличие исключений по условию: максимальная сумма которую можно задолжать банку не может быть отрицательная.

***Ожидаемый результат:*** 
`throw new IllegalArgumentException(
                    "Максимальная сумма которую можно задолжать банку не может быть отрицательная, а у вас: " + creditLimit
            )`.
***Фактический результат:*** в классе CreditAccount _Отсутствует_ ~throw new IllegalArgumentException~ на указанное условие.

## Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by OlesyaSumatokhina** [comment]
Код исправлен, исключение добавлено
