### ISSUE TITLE
Сеттер на метод `CreditLimit` ОТСУТСТВУЕТ в классе `CreditAccount` 

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/Team_project_JAVA#21]
## Описание
В требованиях к классу  `CreditAccount`  `CreditLimit`не может быть меньше 0. Для проверки этого условия необходимо создать  для него setter.

## Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/197a73a36e0087d51295bf8ff1ee47d903a5d5c1/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L95

### Шаги воспроизведения

1. Открыть GitHab;
2. Пройти по ссылке на проект в класс SavingAccount: https://github.com/migbaranes/Team_project_JAVA/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L95
3. Проверить наличие setCreditLimit.

***Ожидаемый результат:***
 в классе CreditAccount есть `public void setCreditLimit(int creditLimit) {
        this.creditLimit = creditLimit;
    }`.
***Фактический результат:*** в классе CreditAccount отсутствует setCreditLimit.

## Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by OlesyaSumatokhina** [comment]
Код исправлен, сеттер добавлен
