### ISSUE TITLE
Код метода `yearChange` в классе `CreditAccount` неправильно считает проценты 

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/Team_project_JAVA#28]
## Описание 
Метод `yearChange` неверно написан код расчёта процентов на остаток счёта при условии, что счёт не будет меняться год. Сумма процентов приводится к целому числу через отбрасывание дробной части. Сперва следует умножить, а затем только разделить, иначе будут гигантские ошибки округления, из-за особенностей целочисленного деления. Попробуйте посчитать сколько вы заработаете со счётом в -99 рублей и ставкой 80% годовых - при текущем подсчёте будет 0 (-99 / 100 * 80 = 0 * 80 = 0

## Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/ed9753d181a4210487dd2e43ad9ad43af16be45c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L110

## Шаги воспроизведения

1. открыть проект на GitHab по ссылке: `https://github.com/migbaranes/Team_project_JAVA/tree/main`;
2. открыть класс `CreditAccount`;
3. посмотреть реализацию `yearChange` ;
4. перейти по ссылке: `https://github.com/migbaranes/Team_project_JAVA/blob/ed9753d181a4210487dd2e43ad9ad43af16be45c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L97`;
5. в тесте `shouldYearChangeToNegativeBalance` выставить `setBalance = -99` , `rate = 80`;
7. запустить тест.

***Ожидаемый результат:***
в консоле `actual = 79`.
***Фактический результат:***
в консоле `actual = 0`.

## Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by OlesyaSumatokhina** [comment]
код объекта yearChange исправлен
