### ISSUE TITLE
Код условия реализации метода `pay` в классе `CreditAccount` описан с ошибкой

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/Team_project_JAVA#29]
## Описание 
Метод `pay`  в классе `CreditAccount.java` это операция оплаты с карты на указанную сумму. В результате успешного вызова этого метода, баланс должен уменьшиться на сумму покупки. Если же операция может привести к некорректному состоянию счёта (например, баланс может уйти меньше чем лимит), то операция должна завершиться вернув `false` и ничего не поменяв на счёте. При реализации написанного кода списываются средства, даже когда операция завершается неуспешно.
Должно реализоваться условие: `(balance - amount >= creditLimit)`. 

## Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/ed9753d181a4210487dd2e43ad9ad43af16be45c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L70

## Шаги воспроизведения

1. Перейти по ссылке: `https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java`.
2. Проверить реализацию метода pay.
4. Для реализации теста сделать `Fork` и `Clone` проекта.
5. В IDEA открыть проект `Team_project_JAVA`, в нём класс CreditAccountTest;
6. В тесте `shouldPayBalanceMoreLimit`, присвоить переменной `amount` значение, при котором после реализации метода `pay` выполниться условие `balance < creditLimit`;
7. запустить тест  shouldPayBalanceMoreLimit в режиме debag.

***Ожидаемый результат:*** 
Реализуется условие `(balance - amount >= creditLimit)` для метода `pay. операция завершиться вернув `false` и ничего не поменяв на счёте.

_Фактический результат:_ 
операция завершается вернув `false`, но счёт меняется на сумму ` amount`.

## Окружение
- Характеристики Windows:
Выпуск Windows 10 Домашняя
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by OlesyaSumatokhina** [comment]
код объекта pay исправлен
