### ISSUE TITLE
Формула расчета неверная при реализации метода `add`

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/Team_project_JAVA#4]
### Описание
В Java класс "CreditAccount.java" неверно составлена формула расчета при реализации метода `add` Расчет не позволяет учитывать начальный баланс на счете.

### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65

### Шаги воспроизведения

1. Зайти в GitHub;
2. Перейти по ссылке: https://github.com/netology-code/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java;
3. Проверить строки #L65-71.

_Ожидаемый результат_: в строке #L69 будет  `balance += amount;`.

_Фактический результат_: в строке #L69 находится  `balance = amount`. 

### Скриншот
![Ком проект невернjt выражение(addCreditAccount)](https://github.com/migbaranes/Team_project_JAVA/assets/149007689/4b130d5b-51f7-4b7d-a226-5620d4e37bcd)

### Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя 
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by OlesyaSumatokhina** [comment]
Код в классе CreditAccount исправлен на верный.

**Comment by OlesyaSumatokhina** [comment]
Код исправлен, суммирование добавлено
