### ISSUE TITLE
Тест НЕ ПРОХОДИТ  при проверке метода `pay` java класса `CreditAccount.java`

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/Team_project_JAVA#5]
### Описание
При проведении функционального тестирования Java класса `CreditAccount.java` тест по проверке метода `pay` выдает неверное значение. Причина в неверно составленном коде.

### Локация дефекта
а) 
https://github.com/migbaranes/Team_project_JAVA/blob/3c507424a9a54f8f09957ea28f04bead76d2dd0f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L35
б) 
https://github.com/migbaranes/Team_project_JAVA/blob/3c507424a9a54f8f09957ea28f04bead76d2dd0f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L48

### Шаги воспроизведения

1. Открыть в IDEA проект `Team_project_JAVA`;
2. Перейти в класс `CreditAccountTest`;
3. Запустить тесты а) `shouldPayToPositiveBalance`,
                               б) `shouldPayToNegativeBalance`.

_Ожидаемый результат_: а) 500,
                                           б) false

_Фактический результат_: а) -3000,
                                            б)  3500.
### Cкриншот
![Ком проект shouldPayToNegativeBalance](https://github.com/migbaranes/Team_project_JAVA/assets/149007689/e2414a3b-692d-4e1e-b1f7-606dc37e94b2)

### Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя 
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by OlesyaSumatokhina** [comment]
Изменен код pay в CreditAccount
