### ISSUE TITLE
Тест НЕ ПРОХОДИТ при проверке метода `YearChange` java класса CreditAccount.java 

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/Team_project_JAVA#6]
### Описание
При проведении функционального тестирования Java класса `CreditAccount.java` тест по проверке метода `YearChange` выдает неверное значение. требуется переопределение метода.

### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/3c507424a9a54f8f09957ea28f04bead76d2dd0f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L71

### Шаги воспроизведения

1. Открыть в IDEA проект `Team_project_JAVA`;
2. Перейти в класс `CreditAccountTest`;
3. Запустить тест  `shouldYearChangeToPositiveBalance`,
                             
_Ожидаемый результат_: `0`

_Фактический результат_: `30`.
### Скриншот

![Ком проект shouldYearChangeToPositiveBalance ](https://github.com/migbaranes/Team_project_JAVA/assets/149007689/9b339ebf-c47f-4c75-b629-b4880bd48f18)

### Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя 
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by OlesyaSumatokhina** [comment]
Объект YearChange переопределен, тесты проходят.
