### ISSUE TITLE
Отсутствует обращение к родительскому классу в классе SavingAccount

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#7]
### Описание
В классе SavingAccount отсутствует отсылка super(), к родительскому классу Account. Это мешает правильно реализоваться методу SavingAccount кода java класса.
### Локация дефекта
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22
### Шаги воспроизведения

1. Зайти в проект на GitHub по ссылке:https://github.com/migbaranes/Team_project_JAVA/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java
2. Проверить строки #22-23.

_Ожидаемый результат_: в строке #22  будет super(balance, rate).

_Фактический результат_: в строке #23 находится if (rate < 0). 

### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/4bb31cc5-535c-48db-af3b-c27d476d7167)
### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
## Исправлено. Закрыто.
