### ISSUE TITLE
Не хватает класса IllegalArgumentException для проверки исключений 

### ISSUE THREAD

**Issue by OlesyaSumatokhina** [migbaranes/Team_project_JAVA#9]
### Описание 
В проекте не хватает класса IllegalArgumentException для тестирования исключений на отрицательное значение накопительной ставки.
### Локация дефекта 
https://github.com/migbaranes/Team_project_JAVA/blob/1fb4a857f1e4ced6da2fc8e08244a989d5097ef3/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22
### Шаги воспроизведения

1. Зайти в проект на GitHub по ссылке: https://github.com/migbaranes/Team_project_JAVA;
2. Открыть класс SavingAccount;
3. Проверить строку #24 на наличие IllegalArgumentException;
4. Проверить папку main проекта на наличие класса IllegalArgumentException.

_Ожидаемый результат_: в папке проекта main находится класс IllegalArgumentException.
_Фактический результат:_ в папке проекта main отсутствует класс IllegalArgumentException.
### Скриншот
![image](https://github.com/migbaranes/Team_project_JAVA/assets/149322645/9d4b3b34-2342-4089-87eb-76be65daf222)
### Окружение

- Характеристики Windows:

Выпуск Windows 11 Домашняя для одного языка
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by migbaranes** [comment]
## Класс `IllegalArgumentException` добавлен в ветку `saving`
